WebProje2/Models/Siniflar/KargoDetay.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebProje2.Models.Siniflar
{
    public class KargoDetay
    {
        [Key]
        public int KargoDetayID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(300, ErrorMessage = "Açıklama En fazla 300 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Açıklama alanı boş geçilemez !")]
        public string Aciklama { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(10, ErrorMessage = "Takip Kodu En fazla 10 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Takip Kodu boş geçilemez !")]
        public string TakipKodu { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(20, ErrorMessage = "Personel adı En fazla 20 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Personel alanı boş geçilemez !")]
        public string Personel { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(25, ErrorMessage = "Alıcı adı En fazla 25 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Alıcı alanı boş geçilemez !")]
        public string Alici { get; set; }
        [Required(ErrorMessage = "Tarih alanı boş geçilemez !")]
        public DateTime Tarih { get; set; }
    }
}

WebProje2/Controllers/KargoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProje2.Models.Siniflar;

namespace WebProje2.Controllers
{
    public class KargoController : Controller
    {
        Context c = new Context();
        public IActionResult Index(string search)
        {
            var k = from x in c.KargoDetays select x;
            if (!string.IsNullOrEmpty(search))
            {
                k = k.Where(y => y.TakipKodu.Contains(search));
            }
            return View(k.ToList());
        }
        [HttpGet]
        public ActionResult KargoEkle()
        {
            Random rnd = new Random();
            string[] karakterler = { "A", "B", "C", "D", "X", "H", "Y", "Z", "C" };
            int k1, k2, k3;
            k1 = rnd.Next(0, 9);
            k2 = rnd.Next(0, 9);
            k3 = rnd.Next(0, 9);
            int s1, s2, s3;
            s1 = rnd.Next(100, 1000);
            s2 = rnd.Next(10, 99);
            s3 = rnd.Next(10, 99);
            string kod = s1.ToString() + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.takipkod = kod;
            return View();
        }
        [HttpPost]
        public ActionResult KargoEkle(KargoDetay d)
        {
            if (!ModelState.IsValid)
            {
                return View("KargoEkle");
            }
            c.KargoDetays.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KargoDetay(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(degerler);
        }
    }
}

WebProje2/Views/Kargo/Index.cshtml
@using WebProje2.Models.Siniflar

@model List<KargoDetay>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>
        Takip Kodu : @Html.TextBox("search")
        <input type="submit" value="Ara" />
    </p>
}
<br />
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Takip Kodu</th>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var k in Model)
    {
<tr>
    <td>
        @k.TakipKodu
    </td>
    <td>
        @k.Personel
    </td>
    <td>
        @k.Alici
    </td>
    <td>
        @k.Tarih.ToString("dd/MM/yyyy")
    </td>
    <td><a href="/Kargo/KargoDetay/@k.TakipKodu" class="btn btn-success">Detaylar</a></td>
</tr>
    }
</table>
<a href="/Kargo/KargoEkle" class="btn btn-info">Yeni Kargo Girişi</a>

WebProje2/Views/Kargo/KargoDetay.cshtml
@using WebProje2.Models.Siniflar

@model List<KargoTakip>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2 style="color:darkred">Kargo Detayları</h2>
<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Aciklama</td>
            <td>@x.TarihZaman</td>
        </tr>
    }
</table>

WebProje2/Views/Kargo/KargoEkle.cshtml
@model WebProje2.Models.Siniflar.KargoDetay

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Kargo Bilgisi Ekleme İşlemleri</h2>
<br />
<form class="form-group" method="post">
    <p style="color:green">Takip Kodu </p>
    <input type="text" value="@ViewBag.takipkod" name="TakipKodu" class="form-control" readonly style="color:red" />
    <br />
    <p style="color:green">Personel</p>
    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Personel, "", new { @style = "color:red" })
    <br />
    <p style="color:green">Alıcı </p>
    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Alici, "", new { @style = "color:red" })
    <br />
    <p style="color:green">Tarih </p>
    <input class="form-control" type="date" name="Tarih" />
    @Html.ValidationMessageFor(x => x.Tarih, "", new { @style = "color:red" })
    <br />
    <p style="color:green">Açıklama </p>
    @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Aciklama, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>