WebProje2/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebProje2.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int Departmanid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "Deoartman Adı En fazla 30 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Departman adı boş geçilemez !")]
        public string DepartmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }

    }
}

WebProje2/Controllers/DepartmanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebProje2.Models.Siniflar;

namespace WebProje2.Controllers
{
    [Authorize(Roles = "A,B")]
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Departmans.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanEkle");
            }
            try
            {
                c.Departmans.Add(d);
                d.Durum = true;
                c.SaveChanges();
                TempData["added"] = "Departman Başarıyla eklendi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }

        }
        public ActionResult DepartmanSil(int id)
        {
            try
            {
                var dep = c.Departmans.Find(id);
                dep.Durum = false;
                c.SaveChanges();
                TempData["deleted"] = "Departman Başarıyla Silindi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }


        }
        public ActionResult DepartmanGetir(int id)
        {
            var dpt = c.Departmans.Find(id);
            return View("DepartmanGetir",dpt);
        }
        public ActionResult DepartmanGuncelle(Departman p)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanGetir");
            }
            try
            {
                var dpt = c.Departmans.Find(p.Departmanid);
                dpt.DepartmanAd = p.DepartmanAd;
                c.SaveChanges();
                TempData["updated"] = "Departman Başarıyla Güncellendi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
         
        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Include(x=>x.Departman).Where(x => x.Departmanid == id).ToList();
            var dpt = c.Departmans.Where(x => x.Departmanid == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.depAdi = dpt;
            return View(degerler);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets
                .Include(x=>x.Urun)
                .Include(x=>x.Cariler)
                .Where(x => x.Personelid == id).ToList();
            var ilgiliPersonel = c.Personels.Where(x => x.PersonelID == id).Select(y => y.PersonelAd+" "+y.PersonelSoyad).FirstOrDefault();
            ViewBag.dPer = ilgiliPersonel;
            return View(degerler);
        }
    }
}

WebProje2/Views/Departman/DepartmanDetay.cshtml
@using WebProje2.Models.Siniflar
@model List<Personel>

@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Detay Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="color:blueviolet">İlgili Departman : @ViewBag.depAdi</li>
</ol>
<br />
<table class="table table-hover">
    <tr>
        <th>Personel ID</th>
        <th>Personel Adı</th>
        <th>Personel Soyadı</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.PersonelID</td>
            <td>@x.PersonelAd</td>
            <td>@x.PersonelSoyad</td>
            <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-primary">Satışlar</a></td>
        </tr>
    }


</table>

WebProje2/Views/Departman/DepartmanEkle.cshtml
@model WebProje2.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Departman Ekleme İşlemleri</h2>
<br />
<form class="form-group" method="post">
    <p style="color:green">Departman Adı </p>
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.DepartmanAd, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

WebProje2/Views/Departman/DepartmanGetir.cshtml
@model WebProje2.Models.Siniflar.Departman

@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Güncelleme İşlemleri</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        <p style="color:darkgoldenrod">Departman Adı</p>
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(x=>x.DepartmanAd,"",new { @style = "color:red" })
        @Html.HiddenFor(x => x.Departmanid)
    </div>
    <button class="btn btn-warning">Güncelle</button>
}

WebProje2/Views/Departman/DepartmanPersonelSatis.cshtml
@using WebProje2.Models.Siniflar
@model List<SatisHareket>

@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satış Bilgileri</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="color:blueviolet">Satışı Gerçekleştiren Personel : @ViewBag.dPer</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Fiyat ₺</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar ₺</td>
            <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
            <td><a href="#" class="btn btn-secondary">Yazdır</a></td>
        </tr>
    }

</table>

WebProje2/Views/Departman/Index.cshtml
@using WebProje2.Models.Siniflar

@model List<Departman>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departmanlar</h2>
<br />
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Departman ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detayları Görüntüle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.Departmanid
            </td>

            <td>
                @k.DepartmanAd
            </td>
            <td><a href="/Departman/DepartmanSil/@k.Departmanid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.Departmanid" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@k.Departmanid" class="btn btn-warning" style="color:white">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-info">Departman Ekle</a>
<p></p>
@if (TempData["added"] != null)
{
    <strong style="color:darkgreen">@TempData["added"]</strong>
}
@if (TempData["deleted"] != null)
{
    <strong style="color:red">@TempData["deleted"]</strong>
}
@if (TempData["updated"] != null)
{
    <strong style="color:darkblue">@TempData["updated"]</strong>
}