WebProje2/Controllers/SatisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebProje2.Models.Siniflar;

namespace WebProje2.Controllers
{
    [Authorize(Roles = "A,B")]
    public class SatisController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
            var degerler = c.SatisHarekets
                .Include(x => x.Personel)
                .Include(x=>x.Urun)
                .Include(x => x.Cariler)
                .ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.Where(x => x.Durum == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from x in c.Carilers.Where(x=>x.Durum==true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd+ " "+x.CariSoyad,
                                               Value = x.CarilerID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd+ " "+x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;

            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            c.SatisHarekets.Add(s);
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.Where(x => x.Durum == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from x in c.Carilers.Where(x => x.Durum == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CarilerID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            var deger = c.SatisHarekets.Find(id);
            return View("SatisGetir",deger);
        }
        public ActionResult SatisGuncelle(SatisHareket satis)
        {
            var deger = c.SatisHarekets.Find(satis.Satisid);
            deger.CarilerID = satis.CarilerID;
            deger.Adet = satis.Adet;
            deger.Fiyat = satis.Fiyat;
            deger.Personelid = satis.Personelid;
            deger.Tarih = satis.Tarih;
            deger.ToplamTutar = satis.ToplamTutar;
            deger.Urunid = satis.Urunid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets
                .Include(x=>x.Urun)
                .Include(x=>x.Cariler)
                .Include(x=>x.Personel)
                .Where(x => x.Satisid == id).ToList();
            return View(degerler);
        }
    }
}

WebProje2/Views/Satis/Index.cshtml
@using WebProje2.Models.Siniflar

@model List<SatisHareket>

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2 style="color:darkred">Satış Geçmişi</h2>
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px">
    <thead>
        <tr>
            <th>Satış ID</th>
            <th>Ürün Adı</th>
            <th>Ürün Markası</th>
            <th>Cari (Müşteri)</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Birim Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.Satisid
            </td>

            <td>
                @k.Urun.UrunAd
            </td>
            <td>
                @k.Urun.Marka
            </td>
            <td>
                @k.Cariler.CariAd @k.Cariler.CariSoyad
            </td>
            <td>
                @k.Personel.PersonelAd @k.Personel.PersonelSoyad
            </td>
            <td>
                @k.Adet
            </td>
            <td>
                @k.Fiyat
            </td>
            <td>
                @k.ToplamTutar
            </td>
            <td>
                @k.Tarih
            </td>
            @*<td><a href="/Personel/DepartmanSil/@k.Departmanid" class="btn btn-danger">Sil</a></td>*@
            <td><a href="/Satis/SatisGetir/@k.Satisid" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Satis/SatisDetay/@k.Satisid" class="btn btn-warning" style="color:black">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<script>
    $('#tbl1').dataTable({});
</script>

WebProje2/Views/Satis/SatisDetay.cshtml
@using WebProje2.Models.Siniflar
@model List<SatisHareket>

@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Satış Detayı</h2>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün Adı</th>
        <th>Cari (Müşteri)</th>
        <th>Ürün Markası</th>
        <th>Personel</th>
        <th>Adet</th>
        <th>Birim Fiyat</th>
        <th>Toplam Tutar</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Urun.Marka</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Adet</td>
            <td>@x.Fiyat</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
        </tr>
    }

</table>
<button class="btn btn-primary">Satış Yazdır</button>

WebProje2/Views/Satis/SatisGetir.cshtml
@model WebProje2.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış İşlemi Güncelleme İşlemleri</h2>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Satisid)
    <p>Ürün Adı</p>
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <p>Ürün Markası</p>
    @Html.TextBoxFor(x=>x.Urun.Marka, new { @class = "form-control" })
    <br />
    <p>Cari(Müşteri)</p>
    @Html.DropDownListFor(x => x.CarilerID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    <p>Personel (Satış Yapan)</p>
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <p>Ürün Adedi</p>
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    <p>Birim Fiyatı</p>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    <p>Toplam Tutar</p>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <p>Satış Tarihi</p>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Satış Bilgilerini Güncelle</button>
}

WebProje2/Views/Satis/YeniSatis.cshtml
@model WebProje2.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış Yapma İşlemleri</h2>
<br />
<form class="form-group" method="post">
    <p>Ürün Adı</p>
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <p>Cari(Müşteri)</p>
    @Html.DropDownListFor(x => x.CarilerID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    <p>Personel</p>
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <p>Adet</p>
   <input type="number" class="form-control"max="10" min="1" placeholder="adet giriniz." name="Adet" id="txt1" onchange="sum();"/>
    <br />
    <p>Birim Fiyat</p>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control",@id="txt2",@onkeyup="sum();" })
    <br />
    <p>Toplam Tutar</p>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control",@id="txt3"})
    <br />
    <button class="btn btn-primary">Ürünü Kaydet</button>
</form>

<script>
    function sum() {
        var sayi1 = document.getElementById('txt1').value;
        var sayi2 = document.getElementById('txt2').value;
        var sonuc = parseInt(sayi1) * parseInt(sayi2);
        if (!isNaN(sonuc)) {
            document.getElementById('txt3').value = sonuc;
        }
    }
</script>