WebProje2/Models/Siniflar/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebProje2.Models.Siniflar
{
    public class Kategori
    {
        [Key]
        public int KategoriID { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "Kategori Adı En fazla 30 karakter uzunluğunda olabilir.")]
        [Required(ErrorMessage = "Kategori Ad alanı boş geçilemez !")]
        public string KategoriAd { get; set; }
        public ICollection<Urun> Uruns { get; set; }

    }
}

WebProje2/Controllers/KategoriController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebProje2.Models.Siniflar;
using X.PagedList;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    [Authorize(Roles = "A,B")]
    public class KategoriController : Controller
    {
        // GET: Kategori
        Context c = new Context();
        
        public ActionResult Index(int sayfa = 1)
        {
            var degerler = c.Kategoris.ToList().ToPagedList(sayfa, 5);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(Kategori yeniKategori)
        {
            if (!ModelState.IsValid)
            {
                return View("KategoriEkle");
            }
            try
            {
                c.Kategoris.Add(yeniKategori);
                c.SaveChanges();
                TempData["added"] = "Kategori Başarıyla Eklendi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }
 

        }
        public ActionResult KategoriSil(int id)
        {
            try
            {
                var ktg = c.Kategoris.Find(id);
                c.Kategoris.Remove(ktg);
                c.SaveChanges();
                TempData["deleted"] = "Kategori Başarıyla Silindi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }

        }
        public ActionResult KategoriGetir(int id)
        {
            var kategori = c.Kategoris.Find(id);
            return View("KategoriGetir", kategori);
        }
        public ActionResult KategoriGuncelle(Kategori k)
        {
            if (!ModelState.IsValid)
            {
                return View("KategoriGetir");
            }
            try
            {
                var ktgr = c.Kategoris.Find(k.KategoriID);
                ktgr.KategoriAd = k.KategoriAd;
                c.SaveChanges();
                TempData["updated"] = "Kategori Başarıyla Güncellendi.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

WebProje2/Views/Kategori/Index.cshtml
@using WebProje2.Models.Siniflar
@using X.PagedList.Mvc.Core;
@using X.PagedList;

@model IPagedList<Kategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2 style="color:darkred">Kategoriler</h2>
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Kategori ID</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.KategoriID
            </td>

            <td>
                @k.KategoriAd
            </td>
            <td><a href="/Kategori/KategoriSil/@k.KategoriID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kategori/KategoriGetir/@k.KategoriID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa })
, new X.PagedList.Web.Common.PagedListRenderOptions
{
    LiElementClasses = new List<string>
    {"page-link"}
})
<a href="/Kategori/KategoriEkle" class="btn btn-primary">Kategori Ekle</a>
<p></p>
@if (TempData["added"] != null)
{
    <strong style="color:darkgreen">@TempData["added"]</strong>
}
@if (TempData["deleted"] != null)
{
    <strong style="color:red">@TempData["deleted"]</strong>
}
@if (TempData["updated"] != null)
{
    <strong style="color:darkblue">@TempData["updated"]</strong>
}

WebProje2/Views/Kategori/KategoriEkle.cshtml
@model WebProje2.Models.Siniflar.Kategori
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Kategori Ekleme İşlemleri</h2>
<br />
<form class="form-group" method="post">
    @Html.TextBoxFor(x => x.KategoriAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.KategoriAd, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-info" id="btn1">Kaydet</button>
</form>

WebProje2/Views/Kategori/KategoriGetir.cshtml
@model WebProje2.Models.Siniflar.Kategori

@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelleme İşlemleri</h2>
<br />
@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post)) 
{ 
<div class="form-group">
    <p>Kategori Adı </p>
    @Html.TextBoxFor(x => x.KategoriAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.KategoriAd, "", new { @style = "color:red" })
    @Html.HiddenFor(x => x.KategoriID)
</div>
    <button class="btn btn-warning">Güncelle</button>
}